version: "3.9"
services:
  web-server:
    build: "./web-server"
    ports:
      - 3000:3000
    environment:
      - API_GATEWAY_URL=https://localhost:8001/

  api-gateway:
    build: "./api-gateway"
    ports:
      - 8001:8001
    environment:
      - ORDER_API_URL=https://localhost:3531/
      - SANDWICH_API=https://localhost:9055/
      - AUTH_API_URL=https://localhost:6363/
      - RABBITMQ_URL=https://localhost:5672/

  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672
