version: "3.9"
services:
  web-server:
    build: "./web-server"
    ports:
      - 3000:3000

  gateway:
    build: "./api-gateway"

    ports:
      - 8001:8001

    environment:
      - ORDER_API_URL=https://localhost:3531/
      - AUTH_API_URL=https://localhost:6363/
      - RABBITMQ_URL=https://localhost:5672/

  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672
