version: "3.9"
services:
  gateway:
    build: "./api-gateway"

    environment:
      - ORDER_API_URL=https://localhost:3531/
      - AUTH_API_URL=https://localhost:6363/
      - RABBITMQ_URL=https://localhost:5672/

  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672

    
