version: "3.9"
services:
  web-server:
    build: "./web-server"
    ports:
      - 3000:80

  api-gateway:
    build: "./api-gateway"
    ports:
      - 8001:8001
    environment:
      - ORDER_API_URL=http://127.0.0.1:3531/
      - SANDWICH_API=http://127.0.0.1:9055/
      - AUTH_API_URL=http://127.0.0.1:6363/
      - RABBITMQ_URL=http://127.0.0.1:5672/

  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672
